name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run dummy test
        run: |
          echo "No tests yet... Add pytest later"

      - name: Enable Docker daemon
        run: |
          sudo systemctl start docker || true    
      
      - name: Build Docker image
        run: |
          docker build -t todo-api-devops .